# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/piotrek/Desktop/projekt/projekt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/piotrek/Desktop/projekt/projekt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/piotrek/Desktop/projekt/projekt && $(CMAKE_COMMAND) -E cmake_progress_start /home/piotrek/Desktop/projekt/projekt/CMakeFiles /home/piotrek/Desktop/projekt/projekt/src/R_PEAKS/CMakeFiles/progress.marks
	cd /home/piotrek/Desktop/projekt/projekt && $(MAKE) -f CMakeFiles/Makefile2 src/R_PEAKS/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/piotrek/Desktop/projekt/projekt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/piotrek/Desktop/projekt/projekt && $(MAKE) -f CMakeFiles/Makefile2 src/R_PEAKS/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/piotrek/Desktop/projekt/projekt && $(MAKE) -f CMakeFiles/Makefile2 src/R_PEAKS/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/piotrek/Desktop/projekt/projekt && $(MAKE) -f CMakeFiles/Makefile2 src/R_PEAKS/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/piotrek/Desktop/projekt/projekt && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
src/R_PEAKS/CMakeFiles/R_PEAKS.dir/rule:
	cd /home/piotrek/Desktop/projekt/projekt && $(MAKE) -f CMakeFiles/Makefile2 src/R_PEAKS/CMakeFiles/R_PEAKS.dir/rule
.PHONY : src/R_PEAKS/CMakeFiles/R_PEAKS.dir/rule

# Convenience name for target.
R_PEAKS: src/R_PEAKS/CMakeFiles/R_PEAKS.dir/rule
.PHONY : R_PEAKS

# fast build rule for target.
R_PEAKS/fast:
	cd /home/piotrek/Desktop/projekt/projekt && $(MAKE) -f src/R_PEAKS/CMakeFiles/R_PEAKS.dir/build.make src/R_PEAKS/CMakeFiles/R_PEAKS.dir/build
.PHONY : R_PEAKS/fast

# Convenience name for target.
src/R_PEAKS/CMakeFiles/R_PEAKS_automoc.dir/rule:
	cd /home/piotrek/Desktop/projekt/projekt && $(MAKE) -f CMakeFiles/Makefile2 src/R_PEAKS/CMakeFiles/R_PEAKS_automoc.dir/rule
.PHONY : src/R_PEAKS/CMakeFiles/R_PEAKS_automoc.dir/rule

# Convenience name for target.
R_PEAKS_automoc: src/R_PEAKS/CMakeFiles/R_PEAKS_automoc.dir/rule
.PHONY : R_PEAKS_automoc

# fast build rule for target.
R_PEAKS_automoc/fast:
	cd /home/piotrek/Desktop/projekt/projekt && $(MAKE) -f src/R_PEAKS/CMakeFiles/R_PEAKS_automoc.dir/build.make src/R_PEAKS/CMakeFiles/R_PEAKS_automoc.dir/build
.PHONY : R_PEAKS_automoc/fast

R_PEAKS_EMD.o: R_PEAKS_EMD.cpp.o
.PHONY : R_PEAKS_EMD.o

# target to build an object file
R_PEAKS_EMD.cpp.o:
	cd /home/piotrek/Desktop/projekt/projekt && $(MAKE) -f src/R_PEAKS/CMakeFiles/R_PEAKS.dir/build.make src/R_PEAKS/CMakeFiles/R_PEAKS.dir/R_PEAKS_EMD.cpp.o
.PHONY : R_PEAKS_EMD.cpp.o

R_PEAKS_EMD.i: R_PEAKS_EMD.cpp.i
.PHONY : R_PEAKS_EMD.i

# target to preprocess a source file
R_PEAKS_EMD.cpp.i:
	cd /home/piotrek/Desktop/projekt/projekt && $(MAKE) -f src/R_PEAKS/CMakeFiles/R_PEAKS.dir/build.make src/R_PEAKS/CMakeFiles/R_PEAKS.dir/R_PEAKS_EMD.cpp.i
.PHONY : R_PEAKS_EMD.cpp.i

R_PEAKS_EMD.s: R_PEAKS_EMD.cpp.s
.PHONY : R_PEAKS_EMD.s

# target to generate assembly for a file
R_PEAKS_EMD.cpp.s:
	cd /home/piotrek/Desktop/projekt/projekt && $(MAKE) -f src/R_PEAKS/CMakeFiles/R_PEAKS.dir/build.make src/R_PEAKS/CMakeFiles/R_PEAKS.dir/R_PEAKS_EMD.cpp.s
.PHONY : R_PEAKS_EMD.cpp.s

R_PEAKS_Hilbert.o: R_PEAKS_Hilbert.cpp.o
.PHONY : R_PEAKS_Hilbert.o

# target to build an object file
R_PEAKS_Hilbert.cpp.o:
	cd /home/piotrek/Desktop/projekt/projekt && $(MAKE) -f src/R_PEAKS/CMakeFiles/R_PEAKS.dir/build.make src/R_PEAKS/CMakeFiles/R_PEAKS.dir/R_PEAKS_Hilbert.cpp.o
.PHONY : R_PEAKS_Hilbert.cpp.o

R_PEAKS_Hilbert.i: R_PEAKS_Hilbert.cpp.i
.PHONY : R_PEAKS_Hilbert.i

# target to preprocess a source file
R_PEAKS_Hilbert.cpp.i:
	cd /home/piotrek/Desktop/projekt/projekt && $(MAKE) -f src/R_PEAKS/CMakeFiles/R_PEAKS.dir/build.make src/R_PEAKS/CMakeFiles/R_PEAKS.dir/R_PEAKS_Hilbert.cpp.i
.PHONY : R_PEAKS_Hilbert.cpp.i

R_PEAKS_Hilbert.s: R_PEAKS_Hilbert.cpp.s
.PHONY : R_PEAKS_Hilbert.s

# target to generate assembly for a file
R_PEAKS_Hilbert.cpp.s:
	cd /home/piotrek/Desktop/projekt/projekt && $(MAKE) -f src/R_PEAKS/CMakeFiles/R_PEAKS.dir/build.make src/R_PEAKS/CMakeFiles/R_PEAKS.dir/R_PEAKS_Hilbert.cpp.s
.PHONY : R_PEAKS_Hilbert.cpp.s

R_PEAKS_PanTompkins.o: R_PEAKS_PanTompkins.cpp.o
.PHONY : R_PEAKS_PanTompkins.o

# target to build an object file
R_PEAKS_PanTompkins.cpp.o:
	cd /home/piotrek/Desktop/projekt/projekt && $(MAKE) -f src/R_PEAKS/CMakeFiles/R_PEAKS.dir/build.make src/R_PEAKS/CMakeFiles/R_PEAKS.dir/R_PEAKS_PanTompkins.cpp.o
.PHONY : R_PEAKS_PanTompkins.cpp.o

R_PEAKS_PanTompkins.i: R_PEAKS_PanTompkins.cpp.i
.PHONY : R_PEAKS_PanTompkins.i

# target to preprocess a source file
R_PEAKS_PanTompkins.cpp.i:
	cd /home/piotrek/Desktop/projekt/projekt && $(MAKE) -f src/R_PEAKS/CMakeFiles/R_PEAKS.dir/build.make src/R_PEAKS/CMakeFiles/R_PEAKS.dir/R_PEAKS_PanTompkins.cpp.i
.PHONY : R_PEAKS_PanTompkins.cpp.i

R_PEAKS_PanTompkins.s: R_PEAKS_PanTompkins.cpp.s
.PHONY : R_PEAKS_PanTompkins.s

# target to generate assembly for a file
R_PEAKS_PanTompkins.cpp.s:
	cd /home/piotrek/Desktop/projekt/projekt && $(MAKE) -f src/R_PEAKS/CMakeFiles/R_PEAKS.dir/build.make src/R_PEAKS/CMakeFiles/R_PEAKS.dir/R_PEAKS_PanTompkins.cpp.s
.PHONY : R_PEAKS_PanTompkins.cpp.s

R_PEAKS_Tools.o: R_PEAKS_Tools.cpp.o
.PHONY : R_PEAKS_Tools.o

# target to build an object file
R_PEAKS_Tools.cpp.o:
	cd /home/piotrek/Desktop/projekt/projekt && $(MAKE) -f src/R_PEAKS/CMakeFiles/R_PEAKS.dir/build.make src/R_PEAKS/CMakeFiles/R_PEAKS.dir/R_PEAKS_Tools.cpp.o
.PHONY : R_PEAKS_Tools.cpp.o

R_PEAKS_Tools.i: R_PEAKS_Tools.cpp.i
.PHONY : R_PEAKS_Tools.i

# target to preprocess a source file
R_PEAKS_Tools.cpp.i:
	cd /home/piotrek/Desktop/projekt/projekt && $(MAKE) -f src/R_PEAKS/CMakeFiles/R_PEAKS.dir/build.make src/R_PEAKS/CMakeFiles/R_PEAKS.dir/R_PEAKS_Tools.cpp.i
.PHONY : R_PEAKS_Tools.cpp.i

R_PEAKS_Tools.s: R_PEAKS_Tools.cpp.s
.PHONY : R_PEAKS_Tools.s

# target to generate assembly for a file
R_PEAKS_Tools.cpp.s:
	cd /home/piotrek/Desktop/projekt/projekt && $(MAKE) -f src/R_PEAKS/CMakeFiles/R_PEAKS.dir/build.make src/R_PEAKS/CMakeFiles/R_PEAKS.dir/R_PEAKS_Tools.cpp.s
.PHONY : R_PEAKS_Tools.cpp.s

R_PEAKS_automoc.o: R_PEAKS_automoc.cpp.o
.PHONY : R_PEAKS_automoc.o

# target to build an object file
R_PEAKS_automoc.cpp.o:
	cd /home/piotrek/Desktop/projekt/projekt && $(MAKE) -f src/R_PEAKS/CMakeFiles/R_PEAKS.dir/build.make src/R_PEAKS/CMakeFiles/R_PEAKS.dir/R_PEAKS_automoc.cpp.o
.PHONY : R_PEAKS_automoc.cpp.o

R_PEAKS_automoc.i: R_PEAKS_automoc.cpp.i
.PHONY : R_PEAKS_automoc.i

# target to preprocess a source file
R_PEAKS_automoc.cpp.i:
	cd /home/piotrek/Desktop/projekt/projekt && $(MAKE) -f src/R_PEAKS/CMakeFiles/R_PEAKS.dir/build.make src/R_PEAKS/CMakeFiles/R_PEAKS.dir/R_PEAKS_automoc.cpp.i
.PHONY : R_PEAKS_automoc.cpp.i

R_PEAKS_automoc.s: R_PEAKS_automoc.cpp.s
.PHONY : R_PEAKS_automoc.s

# target to generate assembly for a file
R_PEAKS_automoc.cpp.s:
	cd /home/piotrek/Desktop/projekt/projekt && $(MAKE) -f src/R_PEAKS/CMakeFiles/R_PEAKS.dir/build.make src/R_PEAKS/CMakeFiles/R_PEAKS.dir/R_PEAKS_automoc.cpp.s
.PHONY : R_PEAKS_automoc.cpp.s

r_peaks_hard_coded_data.o: r_peaks_hard_coded_data.cpp.o
.PHONY : r_peaks_hard_coded_data.o

# target to build an object file
r_peaks_hard_coded_data.cpp.o:
	cd /home/piotrek/Desktop/projekt/projekt && $(MAKE) -f src/R_PEAKS/CMakeFiles/R_PEAKS.dir/build.make src/R_PEAKS/CMakeFiles/R_PEAKS.dir/r_peaks_hard_coded_data.cpp.o
.PHONY : r_peaks_hard_coded_data.cpp.o

r_peaks_hard_coded_data.i: r_peaks_hard_coded_data.cpp.i
.PHONY : r_peaks_hard_coded_data.i

# target to preprocess a source file
r_peaks_hard_coded_data.cpp.i:
	cd /home/piotrek/Desktop/projekt/projekt && $(MAKE) -f src/R_PEAKS/CMakeFiles/R_PEAKS.dir/build.make src/R_PEAKS/CMakeFiles/R_PEAKS.dir/r_peaks_hard_coded_data.cpp.i
.PHONY : r_peaks_hard_coded_data.cpp.i

r_peaks_hard_coded_data.s: r_peaks_hard_coded_data.cpp.s
.PHONY : r_peaks_hard_coded_data.s

# target to generate assembly for a file
r_peaks_hard_coded_data.cpp.s:
	cd /home/piotrek/Desktop/projekt/projekt && $(MAKE) -f src/R_PEAKS/CMakeFiles/R_PEAKS.dir/build.make src/R_PEAKS/CMakeFiles/R_PEAKS.dir/r_peaks_hard_coded_data.cpp.s
.PHONY : r_peaks_hard_coded_data.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... R_PEAKS"
	@echo "... R_PEAKS_automoc"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... R_PEAKS_EMD.o"
	@echo "... R_PEAKS_EMD.i"
	@echo "... R_PEAKS_EMD.s"
	@echo "... R_PEAKS_Hilbert.o"
	@echo "... R_PEAKS_Hilbert.i"
	@echo "... R_PEAKS_Hilbert.s"
	@echo "... R_PEAKS_PanTompkins.o"
	@echo "... R_PEAKS_PanTompkins.i"
	@echo "... R_PEAKS_PanTompkins.s"
	@echo "... R_PEAKS_Tools.o"
	@echo "... R_PEAKS_Tools.i"
	@echo "... R_PEAKS_Tools.s"
	@echo "... R_PEAKS_automoc.o"
	@echo "... R_PEAKS_automoc.i"
	@echo "... R_PEAKS_automoc.s"
	@echo "... r_peaks_hard_coded_data.o"
	@echo "... r_peaks_hard_coded_data.i"
	@echo "... r_peaks_hard_coded_data.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/piotrek/Desktop/projekt/projekt && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

